runtime: python
env: flex
entrypoint: gunicorn -b :$PORT -k uvicorn.workers.UvicornWorker main:app

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.6
  disk_size_gb: 10
